#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 13 19:40:00 2019

@author: jorgeagr
"""

import numpy as np

def trainPerceptron(x_data, y_data, learning_rate=1e-3, threshold=1e-5, max_iters=100):
    '''
    x_data: Data matrix in row form. Rows are instances, cols are attributes.
    '''
    w = np.zeros((x_data.shape[1], 1))
    x = x_data.T
    
    